
/**
 * 此段代码是由netbeans自动生成的
 * settingPanel的可视化设置
 *
 * PropertyPanel.java
 *
 * Created on 2010-10-15, 23:32:58
 */

package mysnake.settingground;

/**
 *
 * @author Administrator
 */
public class PropertyPanel extends javax.swing.JPanel {

    /** Creates new form PropertyPanel */
    public PropertyPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        webStyleButtonGroup = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        styleButton1 = new javax.swing.JRadioButton();
        styleButton2 = new javax.swing.JRadioButton();
        styleButton0 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        styleButton3 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        backgroundComboBox = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        foodComboBox = new javax.swing.JComboBox();
        snakeComboBox = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        webComboBox = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        foodSiteLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        snakeSiteLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        snakeLengthLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        directionLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        speedLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        ruleText = new javax.swing.JTextArea();

        jPanel4.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jPanel4.setDoubleBuffered(true);

        webStyleButtonGroup.add(styleButton1);
        styleButton1.setSelected(true);
        styleButton1.setText("样式一");
        styleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                styleButton1ActionPerformed(evt);
            }
        });

        webStyleButtonGroup.add(styleButton2);
        styleButton2.setText("样式二");

        webStyleButtonGroup.add(styleButton0);
        styleButton0.setText("不显示");

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("网格");

        webStyleButtonGroup.add(styleButton3);
        styleButton3.setText("样式三");
        styleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                styleButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(styleButton3)
                            .addComponent(styleButton2)
                            .addComponent(styleButton1)
                            .addComponent(styleButton0))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(styleButton0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(styleButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(styleButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(styleButton3)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        backgroundComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "黑色", "蓝色", "青色", "深灰色", "灰色", "绿色", "浅灰色", "洋红色", "橘黄色", "粉红色", "红色", "白色", "黄色" }));
        backgroundComboBox.setSelectedIndex(3);
        backgroundComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backgroundComboBoxActionPerformed(evt);
            }
        });

        jLabel13.setText("背景：");

        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("颜色设置");

        foodComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "黑色", "蓝色", "青色", "深灰色", "灰色", "绿色", "浅灰色", "洋红色", "橘黄色", "粉红色", "红色", "白色", "黄色" }));
        foodComboBox.setSelectedIndex(5);

        snakeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "黑色", "蓝色", "青色", "深灰色", "灰色", "绿色", "浅灰色", "洋红色", "橘黄色", "粉红色", "红色", "白色", "黄色" }));
        snakeComboBox.setSelectedIndex(10);

        jLabel11.setText(" 蛇 ：");

        jLabel15.setText("网格：");

        webComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "黑色", "蓝色", "青色", "深灰色", "灰色", "绿色", "浅灰色", "洋红色", "橘黄色", "粉红色", "红色", "白色", "黄色" }));
        webComboBox.setSelectedIndex(3);

        jLabel12.setText("食物：");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(foodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(webComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backgroundComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(snakeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                        .addGap(49, 49, 49)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(snakeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backgroundComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(foodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(webComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        foodSiteLabel.setText("11,4");

        jLabel9.setText("食物坐标：");

        snakeSiteLabel.setText("5,4");

        jLabel7.setText("蛇头坐标：");

        timeLabel.setText("0秒");

        snakeLengthLabel.setText("4");

        jLabel3.setText("方向：");

        directionLabel.setText("右，→");

        jLabel5.setText("时间：");

        jLabel1.setText("蛇长：");

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("状态栏");

        jLabel6.setText("当前速度：");

        speedLabel.setText("格 /100毫秒");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(snakeLengthLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(directionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(snakeSiteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(foodSiteLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(speedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(snakeSiteLabel)
                    .addComponent(jLabel7)
                    .addComponent(snakeLengthLabel)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foodSiteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel3)
                    .addComponent(directionLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(timeLabel)
                    .addComponent(jLabel6)
                    .addComponent(speedLabel))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        ruleText.setColumns(20);
        ruleText.setEditable(false);
        ruleText.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        ruleText.setForeground(new java.awt.Color(0, 0, 255));
        ruleText.setLineWrap(true);
        ruleText.setRows(5);
        ruleText.setText("规则：\n    1,方向键或WASD控制方向;\n    2,F11、F12或Z、X键可以加减速度;\n    3,Enter键暂停、开始;\n    4,可以直接通过拉伸改变窗口大小，但注意不要把食物拉动到窗体外，会导致无法吃到~~\n    5,注意：网格样式一和样式二会覆盖背景;\n    6,BUG之处，还请指正~ O(∩_∩)O谢谢 ！\n\t\t作者：沉默的小老头\n\t\tQQ: 191988637");
        jScrollPane1.setViewportView(ruleText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backgroundComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backgroundComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backgroundComboBoxActionPerformed

    private void styleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_styleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_styleButton1ActionPerformed

    private void styleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_styleButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_styleButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox backgroundComboBox;
    public javax.swing.JLabel directionLabel;
    public javax.swing.JComboBox foodComboBox;
    public javax.swing.JLabel foodSiteLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JTextArea ruleText;
    public javax.swing.JComboBox snakeComboBox;
    public javax.swing.JLabel snakeLengthLabel;
    public javax.swing.JLabel snakeSiteLabel;
    public javax.swing.JLabel speedLabel;
    public javax.swing.JRadioButton styleButton0;
    public javax.swing.JRadioButton styleButton1;
    public javax.swing.JRadioButton styleButton2;
    public javax.swing.JRadioButton styleButton3;
    public javax.swing.JLabel timeLabel;
    public javax.swing.JComboBox webComboBox;
    private javax.swing.ButtonGroup webStyleButtonGroup;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the backgroundComboBox
     */
    public javax.swing.JComboBox getBackgroundComboBox() {
        return backgroundComboBox;
    }

    /**
     * @return the directionLabel
     */
    public javax.swing.JLabel getDirectionLabel() {
        return directionLabel;
    }

    /**
     * @return the foodComboBox
     */
    public javax.swing.JComboBox getFoodComboBox() {
        return foodComboBox;
    }

    /**
     * @return the foodSiteLabel
     */
    public javax.swing.JLabel getFoodSiteLabel() {
        return foodSiteLabel;
    }

    /**
     * @return the ruleText
     */
    public javax.swing.JTextArea getRuleText() {
        return ruleText;
    }

    /**
     * @return the snakeComboBox
     */
    public javax.swing.JComboBox getSnakeComboBox() {
        return snakeComboBox;
    }

    /**
     * @return the snakeLengthLabel
     */
    public javax.swing.JLabel getSnakeLengthLabel() {
        return snakeLengthLabel;
    }

    /**
     * @return the snakeSiteLabel
     */
    public javax.swing.JLabel getSnakeSiteLabel() {
        return snakeSiteLabel;
    }

    /**
     * @return the speedLabel
     */
    public javax.swing.JLabel getSpeedLabel() {
        return speedLabel;
    }

    /**
     * @return the styleButton0
     */
    public javax.swing.JRadioButton getStyleButton0() {
        return styleButton0;
    }

    /**
     * @return the styleButton1
     */
    public javax.swing.JRadioButton getStyleButton1() {
        return styleButton1;
    }

    /**
     * @return the styleButton2
     */
    public javax.swing.JRadioButton getStyleButton2() {
        return styleButton2;
    }

    /**
     * @return the styleButton3
     */
    public javax.swing.JRadioButton getStyleButton3() {
        return styleButton3;
    }

    /**
     * @return the timeLabel
     */
    public javax.swing.JLabel getTimeLabel() {
        return timeLabel;
    }

    /**
     * @return the webComboBox
     */
    public javax.swing.JComboBox getWebComboBox() {
        return webComboBox;
    }

}
